Stub deno package
Running into a build issue which seems to be caused by an inability of
my system to retrieve a tarball from the web.

```
error: failed to run custom build command for `rusty_v8 v0.2.1`

Caused by:
  process didn't exit successfully: `/build/source/target/release/build/rusty_v8-83bf0bbcea41d12e/build-script-build` (exit code: 101)
--- stdout
Downloading https://s3.amazonaws.com/deno.land/gn_ninja_binaries.tar.gz
<urlopen error [Errno -2] Name or service not known>
Retrying in 5 s ...
Downloading https://s3.amazonaws.com/deno.land/gn_ninja_binaries.tar.gz
<urlopen error [Errno -2] Name or service not known>
Retrying in 10 s ...
Downloading https://s3.amazonaws.com/deno.land/gn_ninja_binaries.tar.gz
<urlopen error [Errno -2] Name or service not known>
Retrying in 20 s ...
Downloading https://s3.amazonaws.com/deno.land/gn_ninja_binaries.tar.gz
<urlopen error [Errno -2] Name or service not known>
Failed to download prebuilt ninja/gn binaries https://s3.amazonaws.com/deno.land/gn_ninja_binaries.tar.gz
Exiting.

--- stderr
thread 'main' panicked at 'assertion failed: status.success()', /build/deno-0.32.0-vendor/rusty_v8/build.rs:138:5
stack backtrace:
   0:     0x555555574c64 - backtrace::backtrace::libunwind::trace::h65597d255cb1398b
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1:     0x555555574c64 - backtrace::backtrace::trace_unsynchronized::hd4f479d7150ec4a0
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2:     0x555555574c64 - std::sys_common::backtrace::_print_fmt::h015072984a2b172c
                               at src/libstd/sys_common/backtrace.rs:77
   3:     0x555555574c64 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h6df05d3335f32194
                               at src/libstd/sys_common/backtrace.rs:61
   4:     0x55555559341c - core::fmt::write::h1f444f4312eb6c27
                               at src/libcore/fmt/mod.rs:1028
   5:     0x555555571827 - std::io::Write::write_fmt::h8d147888220078ef
                               at src/libstd/io/mod.rs:1412
   6:     0x55555557714e - std::sys_common::backtrace::_print::h8a6df0fa81d6af62
                               at src/libstd/sys_common/backtrace.rs:65
   7:     0x55555557714e - std::sys_common::backtrace::print::h6f05b4733407e509
                               at src/libstd/sys_common/backtrace.rs:50
   8:     0x55555557714e - std::panicking::default_hook::{{closure}}::h0d0a23bd02315dd8
                               at src/libstd/panicking.rs:188
   9:     0x555555576e41 - std::panicking::default_hook::h8d15a9aecb4efac6
                               at src/libstd/panicking.rs:205
  10:     0x5555555777eb - std::panicking::rust_panic_with_hook::hbe174577402a475d
                               at src/libstd/panicking.rs:464
  11:     0x55555555e215 - std::panicking::begin_panic::hcb91b3a097884f6b
  12:     0x55555555dcd9 - build_script_build::build_v8::h43c97ed515bc2e44
  13:     0x55555555be00 - build_script_build::main::hb6a61547e46d98b6
  14:     0x55555555e363 - std::rt::lang_start::{{closure}}::hd3b94ddf798ebf2b
  15:     0x555555577213 - std::rt::lang_start_internal::{{closure}}::h6ea535ec5c50fc3e
                               at src/libstd/rt.rs:48
  16:     0x555555577213 - std::panicking::try::do_call::h631c6408dfccc6f5
                               at src/libstd/panicking.rs:287
  17:     0x55555557dc5a - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:78
  18:     0x555555577ccd - std::panicking::try::hab539b2d1255d635
                               at src/libstd/panicking.rs:265
  19:     0x555555577ccd - std::panic::catch_unwind::hd5e0a26424bd7f34
                               at src/libstd/panic.rs:396
  20:     0x555555577ccd - std::rt::lang_start_internal::h3bdc4c7d98181bf9
                               at src/libstd/rt.rs:47
  21:     0x55555555e1e2 - main
  22:     0x7ffff7bf5b8e - __libc_start_main
  23:     0x55555555b17a - _start
  24:                0x0 - <unknown>
```